// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0--rc1
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tokenring_Send_FullMethodName = "/TokenRing.Tokenring/Send"
)

// TokenringClient is the client API for Tokenring service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenringClient interface {
	Send(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Empty, error)
}

type tokenringClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenringClient(cc grpc.ClientConnInterface) TokenringClient {
	return &tokenringClient{cc}
}

func (c *tokenringClient) Send(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Tokenring_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenringServer is the server API for Tokenring service.
// All implementations must embed UnimplementedTokenringServer
// for forward compatibility.
type TokenringServer interface {
	Send(context.Context, *Token) (*Empty, error)
	mustEmbedUnimplementedTokenringServer()
}

// UnimplementedTokenringServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTokenringServer struct{}

func (UnimplementedTokenringServer) Send(context.Context, *Token) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedTokenringServer) mustEmbedUnimplementedTokenringServer() {}
func (UnimplementedTokenringServer) testEmbeddedByValue()                   {}

// UnsafeTokenringServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenringServer will
// result in compilation errors.
type UnsafeTokenringServer interface {
	mustEmbedUnimplementedTokenringServer()
}

func RegisterTokenringServer(s grpc.ServiceRegistrar, srv TokenringServer) {
	// If the following call pancis, it indicates UnimplementedTokenringServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tokenring_ServiceDesc, srv)
}

func _Tokenring_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenringServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tokenring_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenringServer).Send(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// Tokenring_ServiceDesc is the grpc.ServiceDesc for Tokenring service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tokenring_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TokenRing.Tokenring",
	HandlerType: (*TokenringServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Tokenring_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
